# Importing necessary libraries

In [1]:
import pandas as pd
import numpy as np

In [4]:
df=pd.read_csv('~/Downloads/Churn_Modelling.csv')

In [5]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

# Removing useless columns

In [6]:
X=df.iloc[:,3:13]
X

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
0             1               1        101348.88  
1             0               1        112542.58  
2             1               0        113931.57  
3             0               0         93826.63  
4             1               1         79084.10  
...         ...             ...              ...  
9995          1               0         96270.64  
9996          1               1        101699.77  
9997          0               1         42085.58  
9998          1               0         92888.52  
9999          1               0         38190.78  

[10000 rows x 10 columns]

In [11]:
y=df['Exited']
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

# Data Wrangling
## Encoding - LabelEncoder (Alphabetical order)
- Converting the discrete categoring data into discrete numerical values

In [12]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X["Geography"]=le.fit_transform(X['Geography'])
X

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619          0  Female   42       2       0.00              1   
1             608          2  Female   41       1   83807.86              1   
2             502          0  Female   42       8  159660.80              3   
3             699          0  Female   39       1       0.00              2   
4             850          2  Female   43       2  125510.82              1   
...           ...        ...     ...  ...     ...        ...            ...   
9995          771          0    Male   39       5       0.00              2   
9996          516          0    Male   35      10   57369.61              1   
9997          709          0  Female   36       7       0.00              1   
9998          772          1    Male   42       3   75075.31              2   
9999          792          0  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
0             1               1        101348.88  
1             0               1        112542.58  
2             1               0        113931.57  
3             0               0         93826.63  
4             1               1         79084.10  
...         ...             ...              ...  
9995          1               0         96270.64  
9996          1               1        101699.77  
9997          0               1         42085.58  
9998          1               0         92888.52  
9999          1               0         38190.78  

[10000 rows x 10 columns]

In [16]:
X['Geography'].value_counts()
#France=0,Germany-1,Spain-2

Geography
0    5014
1    2509
2    2477
Name: count, dtype: int64

In [18]:
X['Gender']=le.fit_transform(X['Gender'])
X

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619          0       0   42       2       0.00              1   
1             608          2       0   41       1   83807.86              1   
2             502          0       0   42       8  159660.80              3   
3             699          0       0   39       1       0.00              2   
4             850          2       0   43       2  125510.82              1   
...           ...        ...     ...  ...     ...        ...            ...   
9995          771          0       1   39       5       0.00              2   
9996          516          0       1   35      10   57369.61              1   
9997          709          0       0   36       7       0.00              1   
9998          772          1       1   42       3   75075.31              2   
9999          792          0       0   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
0             1               1        101348.88  
1             0               1        112542.58  
2             1               0        113931.57  
3             0               0         93826.63  
4             1               1         79084.10  
...         ...             ...              ...  
9995          1               0         96270.64  
9996          1               1        101699.77  
9997          0               1         42085.58  
9998          1               0         92888.52  
9999          1               0         38190.78  

[10000 rows x 10 columns]

In [20]:
X['Gender'].value_counts()
#0-Female,1=Male

Gender
1    5457
0    4543
Name: count, dtype: int64

# Splitting data into test and train
- Train=75%
- Test=25%

In [48]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=True)

In [49]:
X_train.shape

(7500, 10)

In [50]:
X_test.shape

(2500, 10)

# Feature Scaling 
## StandardScaler 
- Converting the data of large as well as small scale to a same scale

In [51]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [52]:
X_train[0]

array([ 0.71997988, -0.90457101,  0.91776859,  1.25618088,  0.68308948,
       -1.22860079, -0.91094938,  0.64262086,  0.98333878, -1.48050131])

In [53]:
len(X_train[0])

10

# ANN Model

# Importing keras libraries and packages

In [33]:
pip install keras

DEPRECATION: Loading egg at /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/jupyter-1.0.0-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
Note: you may need to restart the kernel to use updated packages.


In [54]:
import keras
#For building Neural Network layer by layer
from keras.models import Sequential

In [55]:
#To randomly initialize the weights to small numbers close to 0(But not 0)
from keras.layers import Dense

# Initializing the ANN
- 2 ways
  - Defining each layer one by one
  - Defining a graph

In [56]:
classifier = Sequential()

# Adding the input layer and the first hidden layer

In [57]:
#Activation function is Rectifier Activation Function (ReLu)

In [58]:
?classifier.add

In [59]:
#input layer
classifier.add(Dense(5,kernel_initializer='glorot_uniform',activation='relu',input_dim=10))
# glorot_uniform - produces random weight
# input_dim=10 as X_train and X_test contains 10 features
# 5 : Pass 5 inputs to the next layer (hidden layer)

In [60]:
#Adding to hidden layer 1 (Second layer)
classifier.add(Dense(5,kernel_initializer='uniform',activation='relu'))
#Adding the output layer
classifier.add(Dense(1,kernel_initializer='uniform',activation='sigmoid'))
#Output layer has only 1 feature
#Activation is sigmoid whenever we have to use classification problem 

# Compile the model


In [61]:
#Adjusting the weights done by optimizer
#loss is taken binary as it is a classification problem 
#Metrics is accuary
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

# Training model with data

In [62]:
#batches -8000 in 10 batches so each batch as 800
#epochs means how many time we want to adjust the weight
#With every iteration we can see that loss is decreasing while accuracy is increasing
classifier.fit(X_train,y_train,batch_size=10,epochs=100)

Epoch 1/100
750/750 [==============================] - 1s 472us/step - loss: 0.5060 - accuracy: 0.7973
Epoch 2/100
750/750 [==============================] - 0s 458us/step - loss: 0.4460 - accuracy: 0.7977
Epoch 3/100
750/750 [==============================] - 0s 482us/step - loss: 0.4370 - accuracy: 0.7977
Epoch 4/100
750/750 [==============================] - 0s 464us/step - loss: 0.4324 - accuracy: 0.7977
Epoch 5/100
750/750 [==============================] - 0s 462us/step - loss: 0.4292 - accuracy: 0.8021
Epoch 6/100
750/750 [==============================] - 0s 463us/step - loss: 0.4266 - accuracy: 0.8187
Epoch 7/100
750/750 [==============================] - 0s 457us/step - loss: 0.4249 - accuracy: 0.8236
Epoch 8/100
750/750 [==============================] - 0s 459us/step - loss: 0.4229 - accuracy: 0.8240
Epoch 9/100
750/750 [==============================] - 0s 460us/step - loss: 0.4213 - accuracy: 0.8269
Epoch 10/100
750/750 [==============================] - 0s 460us/step - l

# Making predictions and evaluating the model

In [63]:
y_pred=classifier.predict(X_test)
print(y_pred)

79/79 [==============================] - 0s 429us/step
[[0.15296246]
 [0.13317226]
 [0.28145188]
 ...
 [0.14874609]
 [0.5483282 ]
 [0.18406127]]


In [64]:
#Produces the probabilities
# If p>0.5 =1
# else p=0

In [65]:
churn = []
churn_val =[]
for i in y_pred:
    if i > 0.5:
        churn.append("YES")
        churn_val.append(1)
    else:
        churn.append("NO")
        churn_val.append(0)

In [66]:
from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(y_test,churn_val))

[[1910   70]
 [ 346  174]]


In [70]:
print("Accuracy in percentage:",accuracy_score(y_test,churn_val)*100)

Accuracy in percentage: 83.36


In [71]:
#Accuracy can be increased 
#1.By fine tuning either changing batch size or number of epochs
#2.By cahnging the number of nneurons to be passed to the subsequent hidden layers 
# FINE TUNING:
#Fine-tuning machine learning model uses a pre-trained model, designed for image classification,
#and adapting it to differentiate between cows, horses, and humans. This process includes freezing 
#early layers that capture general features and adjusting later layers to learn task-specific distinctions.